# Site settings
baseurl = "https://mauritsmaks.netlify.com/" # moet met een / eindigen
languageCode = "en-us"
title = "Maurits Maks"
theme = "hugo-artists-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Portfolio Maurits Maks"
	description = "Check out the new portfolio of Maurits Maks, an Industrial Design Engineer specialized in PROTOTYPING and MECHATRONICS."

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "MauritsMaks@gmail.com"


	# Header an navigation
	#
	# To change the header background the 'hero-bg-jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "Maurits Maks"
		shortBio = "Engineering // Design // Prototyping"


	# About section
	#
	# Replace the 'avatar.jpg' under 'static/img' with your own image.
	[params.about]
		title = "About me"
		bio = "**Maurits builds prototypes** by combining knowledge in the field of Mechanics, Electronics and Rapid Prototyping."

		[[params.about.skills]]
			name = "Prototyping"
			value = 10

		[[params.about.skills]]
			name = "CAD"
			value = 9

		[[params.about.skills]]
			name = "Robotics"
			value = 8

		[[params.about.skills]]
			name = "Design"
			value = 7

		[[params.about.skills]]
			name = "Team Work"
			value = 7

		[[params.about.skills]]
			name = "Mechatronics"
			value = 8

	# Contact secion
	[params.contact]
		title = "Contact"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "linkedin"
			link = "https://nl.linkedin.com/in/maurits-maks-963788a6"


	[params.form]
		title = "Let's work together"
		# Form fields
		name = "Name" # Text die boven het invoer veld staat
		email = "Email" # Text die boven het invoer veld staat
		message = "Message" # Text die boven het invoer veld staat
		buttonText = "Send" # Text op de button


	[params.footer]
		copyright = "Published under the Unlicense License." # Text onderaan de website
